name: ScratchCards
version: '${project.version}'
main: me.fenixcrafter.scratchcards.ScratchCards
api-version: 1.12.2
authors: [ FenixCrafter ]
description: Adds scratch cards to minecraft

commands:
  GeefKraslot:
    description: Geef een persoon een kraslot
    usage: /<command> (player)
  KraslotenShop:
    description: Opend de winkel
    usage: /<command>